# packages in environment at /home/dhasade/anaconda3/envs/audits:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aif360                    0.5.0                    pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.05.30           h06a4308_0  
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
comm                      0.1.2            py38h06a4308_0  
contourpy                 1.1.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1            py38h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
exceptiongroup            1.1.3                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0  
folktables                0.0.12                    dev_0    <develop>
fonttools                 4.41.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.0.0            py38h06a4308_0  
importlib-resources       6.0.0                    pypi_0    pypi
importlib_metadata        6.0.0                hd3eb1b0_0  
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.19.2           py38hb070fc8_0  
ipython                   8.12.0           py38h06a4308_0  
jedi                      0.18.1           py38h06a4308_1  
joblib                    1.3.1                    pypi_0    pypi
jupyter_client            8.1.0            py38h06a4308_0  
jupyter_core              5.3.0            py38h06a4308_0  
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libnsl                    2.0.0                h5eee18b_0  
libsodium                 1.0.18               h7b6447c_0  
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
matplotlib                3.7.2                    pypi_0    pypi
matplotlib-inline         0.1.6            py38h06a4308_0  
mpmath                    1.3.0                    pypi_0    pypi
nashpy                    0.0.37                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6            py38h06a4308_0  
networkx                  3.1                      pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.0             py38h06a4308_0  
pandas                    2.0.3                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.0.0                   pypi_0    pypi
pip                       23.1.2           py38h06a4308_0  
platformdirs              2.5.2            py38h06a4308_0  
pluggy                    1.3.0                    pypi_0    pypi
prompt-toolkit            3.0.36           py38h06a4308_0  
prompt_toolkit            3.0.36               hd3eb1b0_0  
psutil                    5.9.0            py38h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pygments                  2.15.1           py38h06a4308_1  
pyparsing                 3.0.9                    pypi_0    pypi
pytest                    7.4.2                    pypi_0    pypi
python                    3.8.17          he550d4f_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python_abi                3.8                      3_cp38    conda-forge
pytz                      2023.3                   pypi_0    pypi
pyzmq                     25.1.0           py38h6a678d5_0  
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                67.8.0           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.42.0               h2c6b66d_0    conda-forge
stack_data                0.2.0              pyhd3eb1b0_0  
sympy                     1.12                     pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.2              py38h5eee18b_0  
traitlets                 5.7.1            py38h06a4308_0  
typing_extensions         4.6.3            py38h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.3                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.38.4           py38h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.16.1                   pypi_0    pypi
zlib                      1.2.13               hd590300_5    conda-forge
